namespace FastenUp.SourceGenerator
{
    public static class Templates
    {
        public const string Tab = "    ";
        public const string Space = " ";
        public const string OpenBracket = "{";
        public const string CloseBracket = "}";
        public const string Semicolon = ";";
        public const string Comma = ", ";
        public const string Colon = ":";
        
        
        public const string Namespace = "namespace";
        public const string Public = "public";
        public const string Class = "class";
        public const string Static = "static";
        public const string Abstract = "abstract";
        public const string Partial = "partial";
        public const string Using = "using";
        
        public const string Disclaimer = "// --- GENERATED BY FASTEN UP SOURCE GENERATOR ---";
    }
}